/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package schoolsystem.userInterface.TSInterface.StudentInterface;

import javax.swing.table.AbstractTableModel;
import java.util.List;
import java.util.Vector;
import schoolsystem.users.Student;
import schoolsystem.users.UserList;

/**
 *
 * @author gustavocamargo
 */
public class gradeViewPanel extends javax.swing.JPanel {
    
    public int position;
    
    public Vector lista = UserList.getStudentList();
    
    
    /**
     * Creates new form gradeViewPanel
     * @param pos
     */
    public gradeViewPanel(int pos) {
        position = pos;
        initComponents();
        Student student = (Student)lista.elementAt(position);
        gradeListModel grades = new gradeListModel(student.getGrades());
        gradeTable.setModel(grades);
        gradeTable.setAutoCreateRowSorter(true);
    }
    
    
    public static class gradeListModel extends AbstractTableModel {

        private final String[] columns = {"Subject", "Grade"};
        private final List<Grade> gradeList;

        public gradeListModel(List<Grade> gradeList) {
            this.gradeList = gradeList;
        }

        @Override
        public int getRowCount() {
            return gradeList.size();
        }

        @Override
        public int getColumnCount() {
            return columns.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
             switch(columnIndex) {
                 case 0:
                     return gradeList.get(rowIndex).getSubject().getSubjectName();
                 case 1:
                     return gradeList.get(rowIndex).getGrade();
                 default:
                     return "-";
            }
        }

        @Override
        public String getColumnName(int column) {
            return columns[column];
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            if (getValueAt(0,columnIndex) != null) {
                return (getValueAt(0,columnIndex).getClass());
            }else {
                return Object.class;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeTable = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Futura", 0, 24)); // NOI18N
        jLabel1.setText("These are your grades");

        jScrollPane1.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N

        gradeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(gradeTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable gradeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
