/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterfaces;

import List.CourAndSubjList;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author dillan
 */
public class CreateCourses extends javax.swing.JPanel {

    /**
     * Creates new form CreateG
     */
    public CreateCourses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CreateGradeButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        GradeList = new javax.swing.JComboBox<>();
        ClassroomList = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(840, 480));

        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(840, 480));

        jLabel2.setFont(new java.awt.Font("Tlwg Typo", 1, 24)); // NOI18N
        jLabel2.setText("Classroom:");

        jLabel3.setFont(new java.awt.Font("Tlwg Typo", 1, 24)); // NOI18N
        jLabel3.setText("Create Matter");

        CreateGradeButton.setFont(new java.awt.Font("TlwgTypewriter", 1, 18)); // NOI18N
        CreateGradeButton.setText("Create");
        CreateGradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateGradeButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tlwg Typo", 1, 24)); // NOI18N
        jLabel4.setText("Grade:");

        GradeList.setFont(new java.awt.Font("TlwgTypewriter", 3, 15)); // NOI18N
        GradeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));

        ClassroomList.setFont(new java.awt.Font("TlwgTypewriter", 3, 15)); // NOI18N
        ClassroomList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(GradeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClassroomList, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(CreateGradeButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GradeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClassroomList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(CreateGradeButton)
                .addGap(129, 129, 129))
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateGradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateGradeButtonActionPerformed

        String gradeL = GradeList.getSelectedItem().toString();
        String classR = ClassroomList.getSelectedItem().toString();
        String name = gradeL + classR;
        
        if(Course.verifyNewCourse(name) == -1){
            Course course = new Course(name);
            CourAndSubjList.addCourse(course);
            JOptionPane.showMessageDialog(null, "Course created successfully");
        } else {
            JOptionPane.showMessageDialog(null, "The course already exists.");
        }

    }//GEN-LAST:event_CreateGradeButtonActionPerformed

//    public void writeFile(Course grade){
//        File file = new File("src/Files/Grades.txt");
//
//        try {
//            PrintWriter exit =  new PrintWriter(new FileWriter(file, true));
//            exit.println(grade.getNameGrade());
//            exit.close();
//        } catch (FileNotFoundException ex){
//            ex.printStackTrace(System.out);
//        } catch (IOException ex) {
//            ex.printStackTrace(System.out);
//        }
//
//    }
//    
//    public boolean checkCourses(Course grade){
//        File file = new File("src/Files/Grades.txt");
//
//        boolean cheak = true;
//
//        try {
//            BufferedReader entry = new BufferedReader(new FileReader(file));
//            String reading = entry.readLine();
//            while (reading != null){
//                if (reading.equals(grade.getNameGrade())){
//                    cheak = false;
//                }
//                reading = entry.readLine();
//            }
//            entry.close();
//        } catch (FileNotFoundException ex){
//            ex.printStackTrace();
//        } catch (IOException ex){
//            ex.printStackTrace();
//        }
//        return cheak;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JComboBox<String> ClassroomList;
    private javax.swing.JButton CreateGradeButton;
    private javax.swing.JComboBox<String> GradeList;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
